constants:

    # Project & Hostname
    project: project_domain
    group: group_server
    hostname: hostname_server

    # Servers
    user_1: user_1
    server_1: server_or_ip_1
    port_1: port_1
    
    user_2: user_2
    server_2: server_or_ip_2
    port_2: port_2

# List of source directories and files to back up
source_directories:
    - /var/www/{project}

exclude_patterns:
    - '*.o'
    - '*.log'
    - '*.tmp'
    - '*.cache'
    - '*.git'

archive_name_format: '{project}_site-files-{now:%Y-%m-%dT%H:%M:%S}'

# Retention policy
keep_monthly: 6
keep_yearly: 1

checks:
    - name: archives
    - name: repository
      frequency: 2 weeks

check_last: 3

# Backup hooks
before_backup:
    - docker compose -f /var/www/{project}/docker-compose.yml down -v
    - docker compose -f /var/www/{project}/docker-compose.yml stop

after_backup:
    - docker compose -f /var/www/{project}/docker-compose.yml up -d
    - docker compose -f /var/www/{project}/docker-compose.yml logs -t > /var/log/{project}_docker.log

on_error:
    - send_notification "Borgmatic" "Error during backup for {project}" "alert"
