#!/bin/sh

# Foreground Colours
#RED='31'
#CYAN='36'

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "${DISTRIB_DESCRIPTION}" ] && [ -x /usr/bin/lsb_release ]; then
	# Fall back to using the very slow lsb_release utility
	DISTRIB_DESCRIPTION="$(lsb_release -s -d)"
fi

printf "\n"

printf "Welcome to %s (%s %s %s)\n" "${DISTRIB_DESCRIPTION}" "$(uname -o)" "$(uname -r)" "$(uname -m)"

printf '\n%s\n' "                                                          "
printf "%40s\n" "██████╗ ██████╗  ██████╗  ██████╗ ██████╗ ███████"
printf "%40s\n" "██╔══██╗██╔══██╗██╔═══██╗██╔═══██╗██╔══██╗██╔══  "
printf "%40s\n" "██████╔╝██████╔╝██║   ██║██║   ██║██████╔╝█████  "
printf "%40s\n" "██╔══██╗██╔══██╗██║   ██║██║   ██║██╔══██╗██╔    "
printf "%40s\n" "██████╔╝██║  ██║╚██████╔╝╚██████╔╝██████╔╝███████"
printf "%40s\n" "╚═════╝ ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚═════╝ ╚══════"
printf "%40s\n" "------------------- SERVER ----------------------"

printf "%40s\n" "Running ${SCRIPT_N} v${SCRIPT_V}"

#printf "%40s\n" "You can generate this tags here: http://patorjk.com/software/taag/"

# if it is non-root user, skip
if [ "$(id -u)" -ne 0 ]; then
    exit 0
fi

printf "%40s\n" "You are loggedin as root, please don't do anything stupid..."
printf '\n%s\n' "                                                          "
